### ISSUE TITLE
ExceptionHandling ins't reachable via AddressablesManager

### ISSUE THREAD

**Issue by VirtualMaestro** [laicasaane/unity-addressables-manager#1]
Hello Laicasaane,
Great lib! 
I've spotted an issue in AddressablesManager (AsyncTaskMethods). The class 'ExceptionHandling' locates in the 'Executer' class (of Test Framework) and mark as private, that's why it is not accessible in AddressablesManager.
Also, the class 'ExceptionHandlingType' doesn't exist.
I'm using Test Framework version 1.1.24
I attached a screenshot.
![image](https://user-images.githubusercontent.com/426870/117824068-7096a680-b26e-11eb-98a2-b9217b92fe3c.png)

Thank you

**Comment by laicasaane** [comment]
My bad. Refactoring + conditional compilation is really a bad mix. I'd forgotten to turn the conditional symbol off when doing renaming. The fix is on the way.

**Comment by laicasaane** [comment]
I've fixed it. Thanks for reporting!
