### ISSUE TITLE
Exception: Attempting to use an invalid operation handle

### ISSUE THREAD

**Issue by zaenzhang** [laicasaane/unity-addressables-manager#3]
![2](https://user-images.githubusercontent.com/23573175/188928784-2eecf1fe-78e3-4f88-8695-646f0a1fdbbd.PNG)
![1](https://user-images.githubusercontent.com/23573175/188928815-ed514978-05e3-4221-891d-7156dd7cf7ea.PNG)

unity version :2021.3.9f1 aa version : 1.19.19
```AddressablesManager.InitializeAsync()``` also have same question
![image](https://user-images.githubusercontent.com/23573175/188930053-ee4f183c-3f48-466a-9d89-7eaa15d3960c.png)
if i use completed callback it becomes normal

**Comment by laicasaane** [comment]
@zhangsanfenggithub Thanks for reporting the bug. I've fixed it in `1.3.0`.

**Comment by zaenzhang** [comment]
> @zhangsanfenggithub Thanks for reporting the bug. I've fixed it in `1.3.0`.

I check the addressables source code and find that it will autonatically release the handle
<img width="763" alt="Screenshot 2022-09-08 145742" src="https://user-images.githubusercontent.com/23573175/189056411-1306bae5-1656-472a-95ae-eb9cd169cfea.png">
so i change this method that it works good
<img width="582" alt="Screenshot 2022-09-08 145816" src="https://user-images.githubusercontent.com/23573175/189056674-dba61000-2b94-4217-b4d5-7e33d8181ad7.png">
by the way ,thanks for your lib which is very useful to me

**Comment by laicasaane** [comment]
@zhangsanfenggithub I've tested the `InitializeAsync` with `UniTask` but no exception is fired. Is it a problem with the `Task` counter-part?

**Comment by laicasaane** [comment]
I've fixed this issue the right way, also corrected the APIs for `Task` version in `1.3.1`
